name: HQS build and deploy for pure python repos

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  deploy_pypi:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_build_pure_python.yml@main
    with: 
      python_folder: "./"
    secrets: inherit
