name: HQS build Sphinx docs for pure rust and pure python repos

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish_documentation:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_publish_documentation_rust_sphinx.yml@main
    with:
      py_interface_folder: "."
      py_docs_folder: "./docs"
    secrets: inherit
