name: HQS CI tests for pure python repos

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]


jobs:
  linting_python:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_pure_python.yml@main
    with: 
      python_folder: "qoqo_myqlm"
      linting_folder: "qoqo_myqlm"

  unittests_python:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_tests_pure_python.yml@main
    with: 
      python_folder: "qoqo_myqlm"
      test_code_coverage: false
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: true
